version: 0.2
env:
  parameter-store:
    ENDPOINT: /migrations/referencedata/endpoint
    USERNAME: /migrations/referencedata/username
    PASSWORD: /migrations/referencedata/password

phases:
  build:
    commands:
      - |
        if [ ! -d "./migrations" ]
        then
          echo "No Migrations present"
          exit 0
        fi
        echo "Processing Migrations"
        RDS_USECASE_PASSWORD_RO=$(aws ssm get-parameter --name /$OPCO/rds/$RDS_USECASE_USERNAME_RO/password --with-decryption | jq .Parameter.Value --raw-output)
        RDS_USECASE_PASSWORD_RW=$(aws ssm get-parameter --name /$OPCO/rds/$RDS_USECASE_USERNAME_RW/password --with-decryption | jq .Parameter.Value --raw-output)
        docker run --rm -v $(pwd)/migrations:/flyway/sql boxfuse/flyway -schemas=$RDS_USECASE_SCHEMA -url=jdbc:mysql://$ENDPOINT -user=$USERNAME -password=$PASSWORD -placeholderReplacement=true -placeholders.SITE_CODE=$SITE_CODE -placeholders.RDS_USECASE_PASSWORD_RO=$RDS_USECASE_PASSWORD_RO -placeholders.RDS_USECASE_PASSWORD_RW=$RDS_USECASE_PASSWORD_RW migrate
